version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
    environment:
      QDRANT__STORAGE__MEMMAP_THRESHOLD: "200000"
      QDRANT__SERVICE__TELEMETRY_DISABLED: "true"
    volumes:
      - qdrant_data:/qdrant/storage
    deploy:
      resources:
        limits:
          memory: 1200M
volumes:
  qdrant_data:
