export const SYSTEM_CODE = {
  // Product related
  CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  INGEST_PRODUCTS_SUCCESS: 'INGEST_PRODUCTS_SUCCESS',
  GET_COLLECTION_INFO_SUCCESS: 'GET_COLLECTION_INFO_SUCCESS',
  DELETE_COLLECTION_SUCCESS: 'DELETE_COLLECTION_SUCCESS',

  // Product business errors
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_ID_DUPLICATE: 'PRODUCT_ID_DUPLICATE',
  PRODUCT_TITLE_DUPLICATE: 'PRODUCT_TITLE_DUPLICATE',
  CREATE_PRODUCT_ERROR: 'CREATE_PRODUCT_ERROR',
  UPDATE_PRODUCT_ERROR: 'UPDATE_PRODUCT_ERROR',
  DELETE_PRODUCT_ERROR: 'DELETE_PRODUCT_ERROR',

  // Chat related
  CHAT_SUCCESS: 'CHAT_SUCCESS',
  CHAT_IMAGE_SUCCESS: 'CHAT_IMAGE_SUCCESS',
  CHAT_ERROR: 'CHAT_ERROR',
  IMAGE_ANALYSIS_ERROR: 'IMAGE_ANALYSIS_ERROR',

  // RAG related
  RAG_SEARCH_ERROR: 'RAG_SEARCH_ERROR',
  RAG_INGEST_ERROR: 'RAG_INGEST_ERROR',
  EMBEDDING_ERROR: 'EMBEDDING_ERROR',
  QDRANT_ERROR: 'QDRANT_ERROR',

  // Device Type related (from your example)
  CREATE_DEVICE_TYPE_SUCCESS: 'CREATE_DEVICE_TYPE_SUCCESS',
  UPDATE_DEVICE_TYPE_SUCCESS: 'UPDATE_DEVICE_TYPE_SUCCESS',
  GET_DEVICE_TYPE_SUCCESS: 'GET_DEVICE_TYPE_SUCCESS',
  GET_DEVICE_TYPES_SUCCESS: 'GET_DEVICE_TYPES_SUCCESS',
  DELETE_DEVICE_TYPE_SUCCESS: 'DELETE_DEVICE_TYPE_SUCCESS',
  DEVICE_TYPE_NOT_FOUND: 'DEVICE_TYPE_NOT_FOUND',
  DEVICE_TYPE_HAS_MODELS: 'DEVICE_TYPE_HAS_MODELS',
  NAME_DUPLICATE: 'NAME_DUPLICATE',
  CREATE_DEVICE_TYPE_ERROR: 'CREATE_DEVICE_TYPE_ERROR',
  UPDATE_DEVICE_TYPE_ERROR: 'UPDATE_DEVICE_TYPE_ERROR',

  // Common
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG',
  INVALID_REQUEST_PARAMS: 'INVALID_REQUEST_PARAMS',
} as const;

export type SystemCode = typeof SYSTEM_CODE[keyof typeof SYSTEM_CODE];
